### ISSUE TITLE
Farmer banned from harvester

### ISSUE THREAD

**Issue by Lemmings23456** [drnick23/drplotter#52]
`2024-05-09T10:36:30.321 harvester harvester_server        : WARNING  Peer 192.168.60.203 is still banned, not connecting to it
2024-05-09T10:36:30.321 harvester harvester               : INFO     Failed to connect to PeerInfo(_ip=IPv4Address('192.168.60.203'), _port=8447)
2024-05-09T10:36:33.323 harvester harvester_server        : WARNING  Peer 192.168.60.203 is still banned, not connecting to it
2024-05-09T10:36:33.324 harvester harvester               : INFO     Failed to connect to PeerInfo(_ip=IPv4Address('192.168.60.203'), _port=8447)
2024-05-09T10:36:36.335 harvester harvester_server        : WARNING  Peer 192.168.60.203 is still banned, not connecting to it
2024-05-09T10:36:36.336 harvester harvester               : INFO     Failed to connect to PeerInfo(_ip=IPv4Address('192.168.60.203'), _port=8447)
2024-05-09T10:36:38.322 harvester chia.plot_sync.sender   : INFO     _send_next_message didn't receive response expected_message_type: plot_sync_start, expected_identifier: {'message_id': 0, 'sync_id': 1715243788, 'timestamp': 1715243788}, message None
2024-05-09T10:36:39.362 harvester harvester_server        : INFO     Connected with farmer PeerInfo(_ip=IPv4Address('192.168.60.203'), _port=8447)
2024-05-09T10:36:39.366 harvester chia.harvester.harvester: INFO     harvester_handshake: {'farmer_public_keys': ['0xa515396e942a2b53bca96bf3d491c6c295f3eb54430b8a0574ccbea6abf6f028de8ee0f77370706ee617ace3009e988c',
                        '0xa0af6be71cc328a1f1ec3b43cfefc7da3bdf0139fcde75f219689ab19aa3b55429272f60d7c7c733a6666d3eb32ffeec'],
 'pool_public_keys': ['0xa0af6be71cc328a1f1ec3b43cfefc7da3bdf0139fcde75f219689ab19aa3b55429272f60d7c7c733a6666d3eb32ffeec']}
2024-05-09T10:36:40.045 harvester drplotter               : INFO     Harvesting 5687 drplots with on disk size 132.84 TiB, after decompression 548.90 eTiB, extra rewards 4.13x
2024-05-09T10:36:48.328 harvester harvester_server        : ERROR    Exception: 'PlotManager' object has no attribute 'drplots', PeerInfo(_ip=IPv4Address('192.168.60.203'), _port=8447). Traceback (most recent call last):
  File "/usr/lib/drharvester/chia/server/ws_connection.py", line 404, in wrapped_coroutine
  File "/usr/lib/drharvester/chia/harvester/harvester_api.py", line 65, in harvester_handshake
  File "/usr/lib/drharvester/chia/plot_sync/sender.py", line 176, in start
  File "/usr/lib/drharvester/chia/plot_sync/sender.py", line 215, in _reset
AttributeError: 'PlotManager' object has no attribute 'drplots'

2024-05-09T10:36:48.330 harvester harvester_server        : ERROR    Exception: 'PlotManager' object has no attribute 'drplots' <class 'AttributeError'>, closing connection PeerInfo(_ip=IPv4Address('192.168.60.203'), _port=8447). Traceback (most recent call last):
  File "/usr/lib/drharvester/chia/server/ws_connection.py", line 425, in _api_call
  File "/usr/lib/drharvester/asyncio/tasks.py", line 445, in wait_for
  File "/usr/lib/drharvester/chia/server/ws_connection.py", line 404, in wrapped_coroutine
  File "/usr/lib/drharvester/chia/harvester/harvester_api.py", line 65, in harvester_handshake
  File "/usr/lib/drharvester/chia/plot_sync/sender.py", line 176, in start
  File "/usr/lib/drharvester/chia/plot_sync/sender.py", line 215, in _reset
AttributeError: 'PlotManager' object has no attribute 'drplots'
`

Using 0.12.1 DrPlotter and 2.2.1 as Full Node
It was running for days without error, I changed nothing.

**Comment by Lemmings23456** [comment]
Unfortunatly I don't ! I changed the farmer, it's now a Raspberry Pi with Chia Farmer 2.3. Until then - no more errors. Still running 0.12.1.
